Repository googleapis/java-trace, pull requests merged in 2020-06, with the labels that each got.

#185 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#176 fix: restore GAPIC v2 retry configs
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/TraceServiceClient.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/TraceServiceSettings.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/package-info.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/stub/GrpcTraceServiceStub.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/stub/TraceServiceStub.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/stub/TraceServiceStubSettings.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/TraceServiceClient.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/TraceServiceSettings.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/stub/GrpcTraceServiceStub.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/stub/TraceServiceStub.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/stub/TraceServiceStubSettings.java
  google-cloud-trace/src/test/java/com/google/cloud/trace/v1/TraceServiceClientTest.java
  google-cloud-trace/src/test/java/com/google/cloud/trace/v2/TraceServiceClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#188 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#187 chore: regenerate with updated protoc
  proto-google-cloud-trace-v1/src/main/java/com/google/devtools/cloudtrace/v1/GetTraceRequest.java
  proto-google-cloud-trace-v1/src/main/java/com/google/devtools/cloudtrace/v1/ListTracesRequest.java
  proto-google-cloud-trace-v1/src/main/java/com/google/devtools/cloudtrace/v1/ListTracesResponse.java
  proto-google-cloud-trace-v1/src/main/java/com/google/devtools/cloudtrace/v1/PatchTracesRequest.java
  proto-google-cloud-trace-v1/src/main/java/com/google/devtools/cloudtrace/v1/Trace.java
  proto-google-cloud-trace-v1/src/main/java/com/google/devtools/cloudtrace/v1/TraceSpan.java
  proto-google-cloud-trace-v1/src/main/java/com/google/devtools/cloudtrace/v1/Traces.java
  proto-google-cloud-trace-v2/src/main/java/com/google/devtools/cloudtrace/v2/AttributeValue.java
  proto-google-cloud-trace-v2/src/main/java/com/google/devtools/cloudtrace/v2/BatchWriteSpansRequest.java
  proto-google-cloud-trace-v2/src/main/java/com/google/devtools/cloudtrace/v2/Module.java
  proto-google-cloud-trace-v2/src/main/java/com/google/devtools/cloudtrace/v2/Span.java
  proto-google-cloud-trace-v2/src/main/java/com/google/devtools/cloudtrace/v2/StackTrace.java
  proto-google-cloud-trace-v2/src/main/java/com/google/devtools/cloudtrace/v2/TruncatableString.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#192 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#194 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#200 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#202 chore: set Ruby namespace in proto options
  proto-google-cloud-trace-v1/src/main/java/com/google/devtools/cloudtrace/v1/TraceProto.java
  proto-google-cloud-trace-v1/src/main/proto/google/devtools/cloudtrace/v1/trace.proto
  proto-google-cloud-trace-v2/src/main/java/com/google/devtools/cloudtrace/v2/TraceProto.java
  proto-google-cloud-trace-v2/src/main/java/com/google/devtools/cloudtrace/v2/TracingProto.java
  proto-google-cloud-trace-v2/src/main/proto/google/devtools/cloudtrace/v2/trace.proto
  proto-google-cloud-trace-v2/src/main/proto/google/devtools/cloudtrace/v2/tracing.proto
  synth.metadata
Labels: cla: yes, context: full

#205 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#211 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-trace/pom.xml
  grpc-google-cloud-trace-v1/pom.xml
  grpc-google-cloud-trace-v2/pom.xml
  pom.xml
  proto-google-cloud-trace-v1/pom.xml
  proto-google-cloud-trace-v2/pom.xml
Labels: cla: yes

#210 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#223 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
