Repository googleapis/java-trace, pull requests merged in 2021-09, with the labels that each got.

#622 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/workflows/ci.yaml
  google-cloud-trace-bom/pom.xml
  google-cloud-trace/pom.xml
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/stub/TraceServiceStubSettings.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/stub/TraceServiceStubSettings.java
  owlbot.py
  pom.xml
  renovate.json
  synth.py
Labels: cla: yes, api: cloudtrace, automerge

#626 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: cloudtrace, automerge

#629 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, kokoro:force-run, api: cloudtrace, automerge

#603 chore: update gapic-generator-java version to 2.1.0
  synth.metadata
Labels: cla: yes, api: cloudtrace, automerge, context: full

#639 chore: make owlbot check required
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: cloudtrace, automerge

#636 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: cloudtrace, automerge

#647 chore: change branch master to main in github configurations
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: cloudtrace, automerge
