Repository googleapis/java-trace, pull requests merged in 2021-03, with the labels that each got.

#438 feat(generator): update protoc to v3.15.3
  proto-google-cloud-trace-v2/src/main/java/com/google/devtools/cloudtrace/v2/AttributeValue.java
  proto-google-cloud-trace-v2/src/main/java/com/google/devtools/cloudtrace/v2/AttributeValueOrBuilder.java
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#434 samples: fix version replace tag
  samples/snapshot/pom.xml
Labels: api: cloudtrace, automerge, cla: yes, samples

#441 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#443 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#444 chore: release 1.2.14-SNAPSHOT
  google-cloud-trace-bom/pom.xml
  google-cloud-trace/pom.xml
  grpc-google-cloud-trace-v1/pom.xml
  grpc-google-cloud-trace-v2/pom.xml
  pom.xml
  proto-google-cloud-trace-v1/pom.xml
  proto-google-cloud-trace-v2/pom.xml
  samples/snapshot/pom.xml
  versions.txt
Labels: api: cloudtrace, cla: yes, type: process

#446 chore(release): update Java microgenerator to 1.0.1
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/TraceServiceClient.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/TraceServiceSettings.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/package-info.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/stub/GrpcTraceServiceCallableFactory.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/stub/GrpcTraceServiceStub.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/stub/TraceServiceStub.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/stub/TraceServiceStubSettings.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/TraceServiceClient.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/TraceServiceSettings.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/package-info.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/stub/GrpcTraceServiceCallableFactory.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/stub/GrpcTraceServiceStub.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/stub/TraceServiceStub.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/stub/TraceServiceStubSettings.java
  google-cloud-trace/src/test/java/com/google/cloud/trace/v1/MockTraceService.java
  google-cloud-trace/src/test/java/com/google/cloud/trace/v1/MockTraceServiceImpl.java
  google-cloud-trace/src/test/java/com/google/cloud/trace/v1/TraceServiceClientTest.java
  google-cloud-trace/src/test/java/com/google/cloud/trace/v2/MockTraceService.java
  google-cloud-trace/src/test/java/com/google/cloud/trace/v2/MockTraceServiceImpl.java
  google-cloud-trace/src/test/java/com/google/cloud/trace/v2/TraceServiceClientTest.java
  proto-google-cloud-trace-v2/src/main/java/com/google/devtools/cloudtrace/v2/ProjectName.java
  proto-google-cloud-trace-v2/src/main/java/com/google/devtools/cloudtrace/v2/SpanName.java
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#448 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#449 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#450 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#451 chore: update gax-java dependency to 1.62
  grpc-google-cloud-trace-v1/src/main/java/com/google/devtools/cloudtrace/v1/TraceServiceGrpc.java
  grpc-google-cloud-trace-v2/src/main/java/com/google/devtools/cloudtrace/v2/TraceServiceGrpc.java
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#453 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#456 chore: update java microgenerator to 1.0.2 Adds request initialization to sample code
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/TraceServiceClient.java
  google-cloud-trace/src/test/java/com/google/cloud/trace/v1/MockTraceServiceImpl.java
  google-cloud-trace/src/test/java/com/google/cloud/trace/v2/MockTraceServiceImpl.java
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full, samples

#457 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#459 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#461 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#462 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#463 chore(java): detect sample-secrets in build.sh
  .kokoro/build.sh
  synth.metadata
Labels: api: cloudtrace, build.sh, cla: yes, context: full, in, sample-secrets, samples

#464 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full
