Repository googleapis/java-trace, pull requests merged in 2021-02, with the labels that each got.

#407 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudtrace, cla: yes, context: partial

#408 build(java): update autorelease branch name check
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#409 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: automerge, cla: yes, context: full

#413 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#412 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#390 chore: update gapic-generator-java to 0.0.18
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/TraceServiceClient.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/stub/GrpcTraceServiceCallableFactory.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/stub/TraceServiceStub.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/stub/TraceServiceStubSettings.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/TraceServiceClient.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/stub/GrpcTraceServiceCallableFactory.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/stub/TraceServiceStub.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/stub/TraceServiceStubSettings.java
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#416 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#418 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#417 chore: update javadoc plugin config link
  pom.xml
Labels: api: cloudtrace, cla: yes

#419 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#420 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#415 chore: update gapic-generator-java to 0.0.20
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/TraceServiceClient.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/package-info.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/stub/GrpcTraceServiceStub.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/TraceServiceClient.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/package-info.java
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/stub/GrpcTraceServiceStub.java
  google-cloud-trace/src/test/java/com/google/cloud/trace/v1/MockTraceServiceImpl.java
  google-cloud-trace/src/test/java/com/google/cloud/trace/v2/MockTraceServiceImpl.java
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#423 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-cloud-trace/src/main/java/com/google/cloud/trace/v1/gapic_metadata.json
  google-cloud-trace/src/main/java/com/google/cloud/trace/v2/gapic_metadata.json
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#427 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#428 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#430 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#437 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes
