Repository googleapis/java-trace, pull requests merged in 2021-04, with the labels that each got.

#467 build: configure branch 1.3.0-sp as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: cloudtrace, automerge, cla: yes

#479 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#480 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#484 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#491 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#468 fix: release initial sp version
  .github/workflows/ci.yaml
Labels: api: cloudtrace, automerge, cla: yes

#510 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes, kokoro:force-run

#507 fix: release scripts from issuing overlapping phases
  .kokoro/build.sh
  .kokoro/dependencies.sh
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full, kokoro:force-run

#512 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes
