Repository googleapis/java-trace, pull requests merged in 2021-01, with the labels that each got.

#385 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, cla: yes

#387 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#389 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#386 chore: update gapic-generator-java to 0.0.16
  google-cloud-trace/src/test/java/com/google/cloud/trace/v2/TraceServiceClientTest.java
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#394 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#395 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#398 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#402 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#403 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: cloudtrace, automerge, cla: yes
