Repository googleapis/java-trace, pull requests merged in 2021-05, with the labels that each got.

#514 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: none

#515 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: cloudtrace, automerge, cla: yes

#521 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#523 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#524 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#528 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#529 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#531 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#534 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes

#535 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: cloudtrace, automerge, cla: yes, context: full

#539 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudtrace, automerge, cla: yes
